remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Personal site | Erik Hartman
description:
  <img src="img/memoji.png" alt="me" style="display:inline-block;margin:auto;"/>
  <p>Researcher @ Dept. infection medicine proteomics, Lund University</p>
  <p><a href="https://www.linkedin.com/in/erik-hartman-155b98170/">https://www.linkedin.com/in/erik-hartman-155b98170/</a></p>
  <p> ORCID:0000-0001-9997-2405 </p>
  <p>This page serves as my personal portfolio/resume, and I publish whatever I feel like on it. This may be my latest articles, posts or code-repositories.
  It's open for everyone, but is partly for myself to keep track of things I have scattered all over the web.</p>

email: erik.hartman@hotmail.com
github_username: ErikHartman
baseurl: .

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  auto_ids: true
