remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Erik Hartman
description: <img src="img/memoji.png" alt="me" style="display:inline-block;margin:auto;"/>

email: erik.hartman@hotmail.com

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  auto_ids: true
