remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: M.Sc. Erik Hartman
description:
  <img src="img/memoji.png" alt="me" style="display:inline-block;margin:auto;"/>
  <a>Researcher @ Dept. infection medicine proteomics, Lund University</a>
  This page serves as my personal portfolio, and I publish whatever I feel like on it. This may be my latest articles, posts or code-repositories.
  It's open for everyone, but is partly for myself to keep track of things I have scattered all over the web.

email: erik.hartman@hotmail.com

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  auto_ids: true
