remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Erik Hartman
description:
  <img src="img/memoji.png" alt="me" width="200" style="display:inline-block;margin:auto;"/>

  Welcome! I am a researcher in computational biology / bioinformatics with a focus on contriving new methods in means to de-convolute [_omics_-data](https://en.wikipedia.org/wiki/Omics).

  Here is my [CV](_docs/CV2023.pdf)

  This page serves as my personal portfolio, and I publish whatever I feel like on it. This may be my latest articles, posts or code-repositories. It's open for everyone, but is partly for myself to keep track of things I have scattered all over the web.

email: erik.hartman@hotmail.com

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  auto_ids: true
