remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Erik Hartman
description: Personal site
email: erik.hartman@hotmail.com

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

  auto_ids: true
